#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${CODEINSIGHT_ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
RELEASE_EVIDENCE_SUMMARY_SCRIPT="${CODEINSIGHT_RELEASE_EVIDENCE_SUMMARY_SCRIPT:-$ROOT_DIR/scripts/release-evidence-summary.sh}"
REPO_ARG=()
BRANCH="main"
HEAD_SHA=""
RUN_ID=""
TAG_NAME=""
OUTPUT_FILE=""
FORCE=0

usage() {
  local status="${1:-2}"
  local stream="/dev/stderr"
  if [ "$status" -eq 0 ]; then
    stream="/dev/stdout"
  fi

  cat >"$stream" <<'EOF'
usage: scripts/archive-release-evidence.sh [options] <tag> [branch]

Writes release evidence to release-evidence/<tag>.md by default. The evidence
is generated by scripts/release-evidence-summary.sh, so CI status, artifact
URLs, downloaded report paths, and release metadata are validated before the
archive file is written.

Options:
  --repo OWNER/REPO  Pass an explicit GitHub repository to evidence summary.
  --head-sha SHA     Check this commit instead of the current HEAD.
  --run-id ID        Use this CI run instead of resolving by head SHA.
  --output PATH      Write to PATH instead of release-evidence/<tag>.md.
  --force            Overwrite an existing output file.
  -h, --help         Show this help.

Environment:
  CODEINSIGHT_ROOT_DIR=/path/to/repo
  CODEINSIGHT_RELEASE_EVIDENCE_SUMMARY_SCRIPT=scripts/release-evidence-summary.sh
EOF
  exit "$status"
}

fail() {
  echo "archive release evidence failed: $*" >&2
  exit 1
}

normalize_tag() {
  local tag="$1"
  case "$tag" in
    v*) printf "%s" "$tag" ;;
    *) printf "v%s" "$tag" ;;
  esac
}

main() {
  local temp_file

  while [ "$#" -gt 0 ]; do
    case "$1" in
      -h | --help)
        usage 0
        ;;
      --repo)
        shift
        if [ "$#" -eq 0 ]; then
          usage
        fi
        REPO_ARG=(--repo "$1")
        ;;
      --head-sha)
        shift
        if [ "$#" -eq 0 ]; then
          usage
        fi
        HEAD_SHA="$1"
        ;;
      --run-id)
        shift
        if [ "$#" -eq 0 ]; then
          usage
        fi
        RUN_ID="$1"
        ;;
      --output)
        shift
        if [ "$#" -eq 0 ]; then
          usage
        fi
        OUTPUT_FILE="$1"
        ;;
      --force)
        FORCE=1
        ;;
      --)
        shift
        break
        ;;
      -*)
        usage
        ;;
      *)
        if [ -z "$TAG_NAME" ]; then
          TAG_NAME="$(normalize_tag "$1")"
        elif [ "$BRANCH" = "main" ]; then
          BRANCH="$1"
        else
          usage
        fi
        ;;
    esac
    shift
  done

  while [ "$#" -gt 0 ]; do
    if [ -z "$TAG_NAME" ]; then
      TAG_NAME="$(normalize_tag "$1")"
    elif [ "$BRANCH" = "main" ]; then
      BRANCH="$1"
    else
      usage
    fi
    shift
  done

  if [ -z "$TAG_NAME" ]; then
    usage
  fi
  if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    fail "tag must look like vX.Y.Z or X.Y.Z: $TAG_NAME"
  fi
  if [ ! -x "$RELEASE_EVIDENCE_SUMMARY_SCRIPT" ]; then
    fail "release evidence summary script is not executable: $RELEASE_EVIDENCE_SUMMARY_SCRIPT"
  fi
  if [ -z "$OUTPUT_FILE" ]; then
    OUTPUT_FILE="$ROOT_DIR/release-evidence/$TAG_NAME.md"
  fi
  if [ -e "$OUTPUT_FILE" ] && [ "$FORCE" -ne 1 ]; then
    fail "output file already exists: $OUTPUT_FILE"
  fi

  mkdir -p "$(dirname "$OUTPUT_FILE")"
  temp_file="$(mktemp)"
  trap 'rm -f "$temp_file"' EXIT INT TERM

  summary_args=("${REPO_ARG[@]}")
  if [ -n "$RUN_ID" ]; then
    summary_args+=(--run-id "$RUN_ID")
  fi
  if [ -n "$HEAD_SHA" ]; then
    summary_args+=(--head-sha "$HEAD_SHA")
  fi
  summary_args+=("$TAG_NAME" "$BRANCH")

  CODEINSIGHT_ROOT_DIR="$ROOT_DIR" \
    "$RELEASE_EVIDENCE_SUMMARY_SCRIPT" "${summary_args[@]}" >"$temp_file"

  mv "$temp_file" "$OUTPUT_FILE"
  trap - EXIT INT TERM

  echo "release evidence written: $OUTPUT_FILE"
  echo "next: review $OUTPUT_FILE before tagging $TAG_NAME"
}

main "$@"
