#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="/tmp/codeinsight-external-beta-cohort-report"
MIN_REPORTS=3
MIN_ROUTE_QUALITY_SCORE="${CODEINSIGHT_EXTERNAL_BETA_COHORT_MIN_ROUTE_QUALITY_SCORE:-70}"
MAX_ITEMS=""
CHECK=false

fail() {
  echo "external beta cohort report failed: $*" >&2
  exit 1
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "missing required command: $1"
  fi
}

usage() {
  cat <<'EOF'
usage: scripts/external-beta-cohort-report.sh [BETA_SUMMARY_OR_DIR ...] [options]

Generate a public handoff bundle from External Beta trial reports. Each input
can be a trial output directory or a beta-summary.json file generated by
scripts/external-beta-trial.sh.

Options:
  --output-dir DIR              Output directory. Default: /tmp/codeinsight-external-beta-cohort-report.
  --min-reports N               Minimum complete cohort size. Default: 3.
  --min-route-quality-score N   Route-quality gate. Default: 70.
  --max-items N                 Maximum fix queue items to emit.
  --check                       Fail unless the cohort is complete and the fix queue is actionable when fixes exist.
  -h, --help                    Show this help text.

Output:
  <output-dir>/external-beta-cohort.md
  <output-dir>/external-beta-cohort-summary.json
  <output-dir>/external-beta-fix-queue.md
  <output-dir>/external-beta-fix-queue.json
  <output-dir>/README.md
  <output-dir>/manifest.json
EOF
}

parse_args() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --output-dir)
        [ "$#" -ge 2 ] || fail "--output-dir requires a path"
        OUTPUT_DIR="$2"
        shift 2
        ;;
      --min-reports)
        [ "$#" -ge 2 ] || fail "--min-reports requires a number"
        MIN_REPORTS="$2"
        shift 2
        ;;
      --min-route-quality-score)
        [ "$#" -ge 2 ] || fail "--min-route-quality-score requires a number"
        MIN_ROUTE_QUALITY_SCORE="$2"
        shift 2
        ;;
      --max-items)
        [ "$#" -ge 2 ] || fail "--max-items requires a number"
        MAX_ITEMS="$2"
        shift 2
        ;;
      --check)
        CHECK=true
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      -*)
        fail "unknown argument: $1"
        ;;
      *)
        INPUTS+=("$1")
        shift
        ;;
    esac
  done
}

validate_args() {
  require_command jq
  require_command ruby

  [ "${#INPUTS[@]}" -gt 0 ] || fail "at least one beta-summary.json file or directory is required"

  case "$MIN_REPORTS" in
    ''|*[!0-9]*) fail "--min-reports must be a positive integer" ;;
  esac
  [ "$MIN_REPORTS" -gt 0 ] || fail "--min-reports must be greater than zero"

  case "$MIN_ROUTE_QUALITY_SCORE" in
    ''|*[!0-9]*) fail "--min-route-quality-score must be a non-negative integer" ;;
  esac

  case "$MAX_ITEMS" in
    ''|*[!0-9]*) [ -z "$MAX_ITEMS" ] || fail "--max-items must be a positive integer" ;;
  esac
  if [ -n "$MAX_ITEMS" ] && [ "$MAX_ITEMS" -le 0 ]; then
    fail "--max-items must be greater than zero"
  fi
}

write_readme() {
  local cohort_json="$1"
  local queue_json="$2"
  local cohort_status queue_status report_count item_count next_action

  cohort_status="$(jq -r '.status' "$cohort_json")"
  queue_status="$(jq -r '.status' "$queue_json")"
  report_count="$(jq -r '.report_count' "$cohort_json")"
  item_count="$(jq -r '.item_count' "$queue_json")"
  next_action="$(jq -r '.next_action' "$cohort_json")"

  cat >"$OUTPUT_DIR/README.md" <<EOF
# External Beta Cohort Handoff

This folder is generated from External Beta trial artifacts. It packages cohort
health and the maintainer fix queue for the local-first AI-agent first-read
routing workflow.

## Summary

- Cohort status: \`$cohort_status\`
- Reports: \`$report_count/$MIN_REPORTS\`
- Route-quality gate: \`>= $MIN_ROUTE_QUALITY_SCORE\`
- Next action: \`$next_action\`
- Fix queue status: \`$queue_status\`
- Fix queue items: \`$item_count\`

## Files

- \`external-beta-cohort.md\`: public cohort summary.
- \`external-beta-cohort-summary.json\`: machine-readable cohort summary.
- \`external-beta-fix-queue.md\`: maintainer fix queue.
- \`external-beta-fix-queue.json\`: machine-readable fix queue.
- \`manifest.json\`: machine-readable handoff package manifest.

## Reproduce

\`\`\`bash
scripts/external-beta-cohort-report.sh \\
  BETA_SUMMARY_OR_DIR... \\
  --output-dir "$OUTPUT_DIR" \\
  --min-reports "$MIN_REPORTS" \\
  --min-route-quality-score "$MIN_ROUTE_QUALITY_SCORE"
\`\`\`
EOF
}

write_manifest() {
  local cohort_json="$1"
  local queue_json="$2"
  local manifest_json="$3"

  jq -n \
    --slurpfile cohort "$cohort_json" \
    --slurpfile queue "$queue_json" \
    --arg output_dir "$OUTPUT_DIR" \
    --arg max_items "$MAX_ITEMS" \
    --argjson min_reports "$MIN_REPORTS" \
    --argjson min_route_quality_score "$MIN_ROUTE_QUALITY_SCORE" \
    --argjson check "$([ "$CHECK" = true ] && printf 'true' || printf 'false')" \
    --argjson inputs "$(printf '%s\n' "${INPUTS[@]}" | jq -R . | jq -s .)" \
    '{
      status: (if $cohort[0].status == "complete" then "pass" else "needs_action" end),
      stage: "external_beta_cohort_handoff",
      output_dir: $output_dir,
      inputs: $inputs,
      options: {
        min_reports: $min_reports,
        min_route_quality_score: $min_route_quality_score,
        max_items: (if $max_items == "" then null else ($max_items | tonumber) end),
        check: $check
      },
      cohort: {
        status: $cohort[0].status,
        report_count: $cohort[0].report_count,
        next_action: $cohort[0].next_action,
        quality_gate: $cohort[0].quality_gate.status
      },
      fix_queue: {
        status: $queue[0].status,
        item_count: $queue[0].item_count
      },
      files: [
        "README.md",
        "external-beta-cohort.md",
        "external-beta-cohort-summary.json",
        "external-beta-fix-queue.md",
        "external-beta-fix-queue.json",
        "manifest.json"
      ],
      artifacts: {
        readme: ($output_dir + "/README.md"),
        cohort_markdown: ($output_dir + "/external-beta-cohort.md"),
        cohort_json: ($output_dir + "/external-beta-cohort-summary.json"),
        fix_queue_markdown: ($output_dir + "/external-beta-fix-queue.md"),
        fix_queue_json: ($output_dir + "/external-beta-fix-queue.json"),
        manifest: ($output_dir + "/manifest.json")
      }
    }' >"$manifest_json"
}

main() {
  local -a INPUTS=()
  parse_args "$@"
  validate_args

  mkdir -p "$OUTPUT_DIR"

  local cohort_md="$OUTPUT_DIR/external-beta-cohort.md"
  local cohort_json="$OUTPUT_DIR/external-beta-cohort-summary.json"
  local queue_md="$OUTPUT_DIR/external-beta-fix-queue.md"
  local queue_json="$OUTPUT_DIR/external-beta-fix-queue.json"
  local manifest_json="$OUTPUT_DIR/manifest.json"
  local -a check_args=()
  local -a queue_args=()

  if [ "$CHECK" = true ]; then
    check_args+=(--check)
  fi
  if [ -n "$MAX_ITEMS" ]; then
    queue_args+=(--max-items "$MAX_ITEMS")
  fi

  "$ROOT_DIR/scripts/external-beta-cohort-summary.sh" \
    "${INPUTS[@]}" \
    --output "$cohort_md" \
    --json "$cohort_json" \
    --min-reports "$MIN_REPORTS" \
    --min-route-quality-score "$MIN_ROUTE_QUALITY_SCORE" \
    "${check_args[@]}"

  "$ROOT_DIR/scripts/external-beta-fix-queue.sh" \
    "$cohort_json" \
    --output "$queue_md" \
    --json "$queue_json" \
    "${queue_args[@]}"

  write_readme "$cohort_json" "$queue_json"
  write_manifest "$cohort_json" "$queue_json" "$manifest_json"

  echo "external beta cohort report written to $OUTPUT_DIR/README.md"
  echo "cohort: $cohort_md"
  echo "cohort_json: $cohort_json"
  echo "fix_queue: $queue_md"
  echo "fix_queue_json: $queue_json"
  echo "manifest: $manifest_json"
}

main "$@"
