#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
usage: scripts/external-beta-cohort-summary.sh [BETA_SUMMARY_OR_DIR ...] [options]

Aggregates External Beta trial reports generated by
scripts/external-beta-trial.sh. Each input can be a beta-summary.json file or a
directory containing beta-summary.json.

Options:
  --output PATH       Markdown output path. Default: /tmp/codeinsight-external-beta-cohort.md.
  --json PATH         JSON summary output path. Default: <output-dir>/external-beta-cohort-summary.json.
  --min-reports N     Minimum complete cohort size. Default: 3.
  --min-route-quality-score N
                      Fail check mode when any report route quality is below N.
  --check             Fail unless at least N reports are present and none are needs_triage.
  -h, --help          Show this help text.

Environment:
  CODEINSIGHT_EXTERNAL_BETA_COHORT_MIN_ROUTE_QUALITY_SCORE
EOF
}

fail() {
  echo "external beta cohort summary failed: $*" >&2
  exit 1
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "missing required command: $1"
  fi
}

main() {
  local output="/tmp/codeinsight-external-beta-cohort.md"
  local json_output=""
  local min_reports="3"
  local min_route_quality_score="${CODEINSIGHT_EXTERNAL_BETA_COHORT_MIN_ROUTE_QUALITY_SCORE:-}"
  local check="false"
  local -a inputs=()

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --output)
        [ "$#" -ge 2 ] || fail "--output requires a path"
        output="$2"
        shift 2
        ;;
      --json)
        [ "$#" -ge 2 ] || fail "--json requires a path"
        json_output="$2"
        shift 2
        ;;
      --min-reports)
        [ "$#" -ge 2 ] || fail "--min-reports requires a number"
        min_reports="$2"
        shift 2
        ;;
      --min-route-quality-score)
        [ "$#" -ge 2 ] || fail "--min-route-quality-score requires a number"
        min_route_quality_score="$2"
        shift 2
        ;;
      --check)
        check="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      -*)
        fail "unknown argument: $1"
        ;;
      *)
        inputs+=("$1")
        shift
        ;;
    esac
  done

  case "$min_reports" in
    ''|*[!0-9]*)
      fail "--min-reports must be a positive integer"
      ;;
  esac
  if [ "$min_reports" -le 0 ]; then
    fail "--min-reports must be greater than zero"
  fi
  if [ -n "$min_route_quality_score" ]; then
    case "$min_route_quality_score" in
      ''|*[!0-9]*)
        fail "--min-route-quality-score must be a non-negative integer"
        ;;
    esac
  fi
  if [ "${#inputs[@]}" -eq 0 ]; then
    fail "at least one beta-summary.json file or directory is required"
  fi

  require_command ruby
  mkdir -p "$(dirname "$output")"
  if [ -z "$json_output" ]; then
    json_output="$(dirname "$output")/external-beta-cohort-summary.json"
  fi
  mkdir -p "$(dirname "$json_output")"

  ruby -rjson -rtime - "$output" "$json_output" "$min_reports" "$check" "$min_route_quality_score" "${inputs[@]}" <<'RUBY'
output = ARGV.fetch(0)
json_output = ARGV.fetch(1)
min_reports = Integer(ARGV.fetch(2))
check = ARGV.fetch(3) == "true"
min_route_quality_score_arg = ARGV.fetch(4)
min_route_quality_score = min_route_quality_score_arg.empty? ? nil : Integer(min_route_quality_score_arg)
inputs = ARGV.drop(5)

allowed_outcomes = %w[
  needs_triage
  route_hit
  route_near_miss
  route_miss
  workflow_friction
  overtrust_risk
]

def fail_with(message)
  warn "external beta cohort summary failed: #{message}"
  exit 1
end

def beta_summary_path(input)
  return File.join(input, "beta-summary.json") if File.directory?(input)
  input
end

def metric(summary, key, default = "")
  summary.dig("adoption_summary", "local_evidence", "metrics", key) || default
end

def route_quality_score(summary)
  score = summary.dig("adoption_summary", "mcp_first_call", "route_quality", "score")
  return nil if score.nil? || score.to_s.empty?
  Integer(score)
rescue ArgumentError, TypeError
  nil
end

reports = inputs.map do |input|
  path = beta_summary_path(input)
  fail_with("missing beta summary: #{path}") unless File.file?(path)

  begin
    summary = JSON.parse(File.read(path))
  rescue JSON::ParserError => error
    fail_with("#{path} is not valid JSON: #{error.message}")
  end

  unless summary["status"] == "pass" && summary["stage"] == "external_beta_trial"
    fail_with("#{path} does not match the external beta trial summary contract")
  end

  outcome = summary["outcome"].to_s
  unless allowed_outcomes.include?(outcome)
    fail_with("#{path} has unknown outcome: #{outcome}")
  end

  score = route_quality_score(summary)

  {
    "path" => path,
    "repository" => summary["repository"].to_s,
    "repository_url" => summary["repository_url"].to_s,
    "task" => summary["task"].to_s,
    "expected_first_read" => summary["expected_first_read"].to_s,
    "install_method" => summary["install_method"].to_s,
    "mcp_client" => summary["mcp_client"].to_s,
    "codeinsight_version" => summary["codeinsight_version"].to_s,
    "outcome" => outcome,
    "private_repo" => summary["private_repo"] == true,
    "first_file" => metric(summary, "first_file"),
    "first_seed_value" => metric(summary, "first_seed_value"),
    "line_reduction" => metric(summary, "line_reduction"),
    "read_less_ratio" => metric(summary, "read_less_ratio", "n/a"),
    "risk_level" => metric(summary, "risk_level"),
    "first_suggested_tool" => metric(summary, "first_suggested_tool"),
    "mcp_first_call_status" => summary.dig("adoption_summary", "mcp_first_call", "status").to_s,
    "route_quality_level" => summary.dig("adoption_summary", "mcp_first_call", "route_quality", "level").to_s,
    "route_quality_score" => score,
    "route_quality_recommended_action" => summary.dig("adoption_summary", "mcp_first_call", "route_quality", "recommended_action").to_s,
    "issue_body" => summary.dig("artifacts", "issue_body").to_s,
    "maintainer_triage" => summary.dig("artifacts", "maintainer_triage").to_s
  }
end

counts = allowed_outcomes.to_h { |outcome| [outcome, 0] }
reports.each { |report| counts[report["outcome"]] += 1 }
quality_failures =
  if min_route_quality_score
    reports.select { |report| report["route_quality_score"].nil? || report["route_quality_score"] < min_route_quality_score }
  else
    []
  end

total = reports.length
needs_triage = counts.fetch("needs_triage")
status =
  if total < min_reports
    "insufficient_reports"
  elsif needs_triage.positive?
    "needs_triage"
  elsif quality_failures.any?
    "quality_gate_failed"
  else
    "complete"
  end

next_action =
  if total < min_reports
    "collect_more_external_beta_reports"
  elsif needs_triage.positive?
    "triage_needs_triage_reports"
  elsif quality_failures.any?
    "fix_low_quality_routes"
  elsif counts.fetch("workflow_friction").positive?
    "fix_workflow_friction"
  elsif counts.fetch("route_miss").positive?
    "fix_route_miss"
  elsif counts.fetch("overtrust_risk").positive?
    "fix_overtrust_risk"
  elsif counts.fetch("route_near_miss").positive?
    "improve_route_near_miss"
  else
    "publish_external_beta_summary"
  end

priority_outcome =
  case next_action
  when "triage_needs_triage_reports" then "needs_triage"
  when "fix_low_quality_routes" then "route_quality_below_threshold"
  when "fix_workflow_friction" then "workflow_friction"
  when "fix_route_miss" then "route_miss"
  when "fix_overtrust_risk" then "overtrust_risk"
  when "improve_route_near_miss" then "route_near_miss"
  else ""
  end

priority_reports =
  if priority_outcome == "route_quality_below_threshold"
    quality_failures
  elsif priority_outcome.empty?
    []
  else
    reports.select { |report| report["outcome"] == priority_outcome }
  end

summary = {
  "status" => status,
  "generated_at" => Time.now.utc.iso8601,
  "min_reports" => min_reports,
  "report_count" => total,
  "complete_cohort" => status == "complete",
  "needs_triage_count" => needs_triage,
  "classification_counts" => counts,
  "quality_gate" => (
    if min_route_quality_score
      {
        "min_route_quality_score" => min_route_quality_score,
        "status" => quality_failures.empty? ? "pass" : "fail",
        "failure_count" => quality_failures.length,
        "failures" => quality_failures.map do |report|
          {
            "path" => report["path"],
            "repository" => report["repository"],
            "task" => report["task"],
            "first_file" => report["first_file"],
            "route_quality_score" => report["route_quality_score"]
          }
        end
      }
    end
  ),
  "next_action" => next_action,
  "priority_outcome" => priority_outcome,
  "priority_reports" => priority_reports,
  "reports" => reports,
  "artifacts" => {
    "markdown" => output,
    "json" => json_output
  }
}

def cell(value)
  value.to_s.gsub("|", "\\|").gsub("\n", " ")
end

rows = reports.map do |report|
  repo = if report["private_repo"]
    "private/redacted"
  elsif !report["repository_url"].empty?
    report["repository_url"]
  else
    report["repository"]
  end

  quality = report["route_quality_score"].nil? ? "n/a" : "#{report["route_quality_level"]} / #{report["route_quality_score"]}"
  "| `#{cell(report["outcome"])}` | #{cell(repo)} | #{cell(report["task"])} | `#{cell(report["first_file"])}` | `#{cell(report["read_less_ratio"])}` | `#{cell(report["mcp_first_call_status"])}` | `#{cell(quality)}` | `#{cell(report["path"])}` |"
end

priority_lines =
  if priority_reports.empty?
    ["- None."]
  else
    priority_reports.map do |report|
      "- `#{report["outcome"]}`: #{report["task"]} -> first file `#{report["first_file"]}` (`#{report["path"]}`)"
    end
  end

File.write(output, <<~MARKDOWN)
  # External Beta Cohort Summary

  This report aggregates External Beta trial artifacts generated by
  `scripts/external-beta-trial.sh`. It is adoption evidence for the
  local-first AI-agent first-read routing workflow, not a compiler-grade
  correctness benchmark.

  ## Summary

  - Status: `#{status}`
  - Reports: `#{total}/#{min_reports}`
  - Complete cohort: `#{status == "complete"}`
  - Needs triage: `#{needs_triage}`
  - Route quality gate: `#{min_route_quality_score ? "#{quality_failures.empty? ? "pass" : "fail"} >= #{min_route_quality_score}" : "not_configured"}`
  - Route quality failures: `#{quality_failures.length}`
  - Next action: `#{next_action}`
  - Priority outcome: `#{priority_outcome.empty? ? "-" : priority_outcome}`

  Outcome counts:

  - `needs_triage`: `#{counts.fetch("needs_triage")}`
  - `route_hit`: `#{counts.fetch("route_hit")}`
  - `route_near_miss`: `#{counts.fetch("route_near_miss")}`
  - `route_miss`: `#{counts.fetch("route_miss")}`
  - `workflow_friction`: `#{counts.fetch("workflow_friction")}`
  - `overtrust_risk`: `#{counts.fetch("overtrust_risk")}`

  ## Reports

  | Outcome | Repository | Task | First file | Read less | MCP first call | Route quality | Summary |
  | --- | --- | --- | --- | ---: | --- | --- | --- |
  #{rows.join("\n")}

  ## Priority Queue

  #{priority_lines.join("\n")}

  ## Check Mode

  Run with `--check` before public handoff. The check passes only when at least
  `#{min_reports}` reports are present, none are still `needs_triage`, and any
  configured route-quality gate passes.
MARKDOWN

File.write(json_output, JSON.pretty_generate(summary) + "\n")

if check && status != "complete"
  message = "cohort is not complete: status=#{status}, reports=#{total}/#{min_reports}, needs_triage=#{needs_triage}"
  message += ", route_quality_failures=#{quality_failures.length}" if min_route_quality_score
  fail_with(message)
end

puts "external beta cohort summary written to #{output}"
puts "summary_json: #{json_output}"
puts "status: #{status}"
puts "quality_gate: #{quality_failures.empty? ? "pass" : "fail"} >= #{min_route_quality_score}" if min_route_quality_score
puts "next_action: #{next_action}"
RUBY
}

main "$@"
