#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMP_DIR=""

cleanup() {
  if [ -n "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
  fi
}

fail() {
  echo "public task routing matrix step summary smoke failed: $*" >&2
  exit 1
}

require_literal() {
  local file="$1"
  local literal="$2"
  local description="$3"

  if ! grep -Fq -- "$literal" "$file"; then
    fail "$file is missing $description"
  fi
}

main() {
  local summary_json
  local step_summary

  TEMP_DIR="$(mktemp -d)"
  trap cleanup EXIT INT TERM

  summary_json="$TEMP_DIR/public-task-routing-matrix-summary.json"
  step_summary="$TEMP_DIR/step-summary.md"

  cat >"$summary_json" <<'EOF'
{
  "generated_by": "scripts/update-public-task-routing-matrix.sh",
  "status": "pass",
  "aggregate": {
    "task_count": 6,
    "expectation_count": 6,
    "total_task_source_lines": 1000,
    "total_selected_lines": 125,
    "total_estimated_tokens": 2400,
    "max_impacted_files": 9,
    "line_reduction": 87.5
  },
  "cases": [
    {
      "case": "express",
      "repository": "<case-root>/express",
      "ref": "ae6dd37680e3a00618d6c8a3e522f0ee4eeba1a4",
      "expect_file": "docs/task-routing-expectations/express.tsv",
      "summary_json": "<output-dir>/express/summary.json",
      "task_count": 4,
      "expectation_count": 4,
      "total_task_source_lines": 800,
      "total_selected_lines": 100,
      "total_estimated_tokens": 1800,
      "max_impacted_files": 9,
      "routes": [
        {
          "task": "understand express application routing behavior",
          "first_file": "lib/express.js",
          "first_reading_focus": "Start with seed file context and primary symbols.",
          "first_reading_question": "What entrypoints define the main flow?",
          "seed_strategy": "auto_task_match",
          "line_reduction": "90.0%",
          "estimated_tokens": 1000,
          "risk_level": "high",
          "impacted_files": 9
        },
        {
          "task": "understand middleware behavior",
          "first_file": "lib/application.js",
          "first_reading_focus": "Start with seed file middleware and handler boundaries.",
          "first_reading_question": "Which middleware or handler boundaries shape the requested flow here?",
          "seed_strategy": "auto_task_match",
          "line_reduction": "85.0%",
          "estimated_tokens": 800,
          "risk_level": "high",
          "impacted_files": 7
        }
      ]
    },
    {
      "case": "gin",
      "repository": "<case-root>/gin",
      "ref": "1d2ce092565e08a8bb7f109fbdbbfdba1ac8fbfb",
      "expect_file": "docs/task-routing-expectations/gin.tsv",
      "summary_json": "<output-dir>/gin/summary.json",
      "task_count": 2,
      "expectation_count": 2,
      "total_task_source_lines": 200,
      "total_selected_lines": 25,
      "total_estimated_tokens": 600,
      "max_impacted_files": 3,
      "routes": [
        {
          "task": "understand gin routing behavior",
          "first_file": "gin.go",
          "first_reading_focus": "Start with seed file context and primary symbols.",
          "first_reading_question": "What entrypoints define the main flow?",
          "seed_strategy": "auto_task_match",
          "line_reduction": "87.5%",
          "estimated_tokens": 600,
          "risk_level": "medium",
          "impacted_files": 3
        }
      ]
    }
  ]
}
EOF

  GITHUB_STEP_SUMMARY="$step_summary" \
    "$ROOT_DIR/scripts/public-task-routing-matrix-step-summary.sh" \
      "$summary_json" \
      codeinsight-public-routing-snapshot \
      https://example.com/artifact \
      https://example.com/run >/dev/null

  require_literal "$step_summary" "## Public Task Routing Matrix" "summary heading"
  require_literal "$step_summary" 'Status: `pass`' "status line"
  require_literal "$step_summary" 'Generated by: `scripts/update-public-task-routing-matrix.sh`' "generator line"
  require_literal "$step_summary" 'Workflow run: [open run](https://example.com/run)' "run link"
  require_literal "$step_summary" 'Workflow artifact: [`codeinsight-public-routing-snapshot`](https://example.com/artifact)' "artifact link"
  require_literal "$step_summary" '| Cases | `2` |' "case count"
  require_literal "$step_summary" '| Tasks | `6` |' "task count"
  require_literal "$step_summary" '| Expectations passed | `6/6` |' "expectations metric"
  require_literal "$step_summary" '| Source lines | `1000` |' "source lines metric"
  require_literal "$step_summary" '| Selected lines | `125` |' "selected lines metric"
  require_literal "$step_summary" '| First-read line reduction | `87.5%` |' "line reduction metric"
  require_literal "$step_summary" '| Estimated tokens | `2400` |' "estimated tokens metric"
  require_literal "$step_summary" '| Max impacted files | `9` |' "max impacted files metric"
  require_literal "$step_summary" '| Case | Ref | Tasks | Expectations | Lines | Reduction | First Files |' "case table heading"
  require_literal "$step_summary" '| `express` | `ae6dd37680e3` | `4` | `4` | `100/800` | `87.5%` | lib/application.js, lib/express.js |' "express row"
  require_literal "$step_summary" '| `gin` | `1d2ce092565e` | `2` | `2` | `25/200` | `87.5%` | gin.go |' "gin row"

  echo "public task routing matrix step summary smoke passed"
}

main "$@"
