#!/usr/bin/env bash
set -euo pipefail

SUMMARY_JSON="${1:-}"
ARTIFACT_NAME="${2:-codeinsight-public-routing-snapshot}"
ARTIFACT_URL="${3:-}"
RUN_URL="${4:-}"
SUMMARY_FILE="${GITHUB_STEP_SUMMARY:-/dev/stdout}"

usage() {
  cat >&2 <<'EOF'
usage: scripts/public-task-routing-matrix-step-summary.sh SUMMARY_JSON [ARTIFACT_NAME] [ARTIFACT_URL] [RUN_URL]

Appends the checked-in public task routing matrix JSON snapshot to the GitHub
Actions step summary. When GITHUB_STEP_SUMMARY is not set, writes to stdout.
RUN_URL defaults to the current GitHub Actions run when standard GITHUB_*
environment variables are available.
EOF
}

fail() {
  echo "public task routing matrix step summary failed: $*" >&2
  exit 1
}

require_summary_contract() {
  if ! jq -e \
    '.generated_by == "scripts/update-public-task-routing-matrix.sh"
      and .status == "pass"
      and (.aggregate | type == "object")
      and (.aggregate.task_count | type == "number")
      and (.aggregate.expectation_count | type == "number")
      and (.aggregate.total_task_source_lines | type == "number")
      and (.aggregate.total_selected_lines | type == "number")
      and (.aggregate.total_estimated_tokens | type == "number")
      and (.aggregate.max_impacted_files | type == "number")
      and (.aggregate.line_reduction | type == "number")
      and ((.quality_gate? == null) or (
        (.quality_gate.min_route_quality_score | type == "number")
        and (.quality_gate.status | type == "string")
        and (.quality_gate.failure_count | type == "number")))
      and (.cases | type == "array")
      and (.cases | length > 0)
      and all(.cases[];
        (.case | type == "string")
        and (.repository | type == "string")
        and (.ref | type == "string")
        and (.expect_file | type == "string")
        and (.summary_json | type == "string")
        and (.task_count | type == "number")
        and (.expectation_count | type == "number")
        and (.total_task_source_lines | type == "number")
        and (.total_selected_lines | type == "number")
        and (.total_estimated_tokens | type == "number")
        and (.max_impacted_files | type == "number")
        and (.routes | type == "array")
        and all(.routes[];
          (.task | type == "string")
          and (.first_file | type == "string")
          and (.first_reading_focus | type == "string")
          and (.first_reading_question | type == "string")
          and (.seed_strategy | type == "string")
          and (.line_reduction | type == "string")
          and (.estimated_tokens | type == "number")
          and (.risk_level | type == "string")
          and (.impacted_files | type == "number")))' \
    "$SUMMARY_JSON" >/dev/null; then
    fail "$SUMMARY_JSON does not match the public task routing matrix summary contract"
  fi
}

metric() {
  local query="$1"
  jq -r "$query" "$SUMMARY_JSON"
}

main() {
  if [ -z "$SUMMARY_JSON" ] || [ "$SUMMARY_JSON" = "-h" ] || [ "$SUMMARY_JSON" = "--help" ]; then
    usage
    exit 2
  fi
  if [ ! -s "$SUMMARY_JSON" ]; then
    fail "$SUMMARY_JSON does not exist or is empty"
  fi
  if ! command -v jq >/dev/null 2>&1; then
    fail "missing required command: jq"
  fi

  require_summary_contract

  if [ -z "$RUN_URL" ] &&
    [ -n "${GITHUB_SERVER_URL:-}" ] &&
    [ -n "${GITHUB_REPOSITORY:-}" ] &&
    [ -n "${GITHUB_RUN_ID:-}" ]; then
    RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
  fi

  {
    printf "## Public Task Routing Matrix\n\n"
    printf 'Status: `%s`\n\n' "$(metric '.status')"
    printf 'Generated by: `%s`\n\n' "$(metric '.generated_by')"
    printf 'Checked-in JSON summary: `%s`\n\n' "$SUMMARY_JSON"
    if [ -n "$RUN_URL" ]; then
      printf 'Workflow run: [open run](%s)\n\n' "$RUN_URL"
    fi
    if [ -n "$ARTIFACT_URL" ]; then
      printf 'Workflow artifact: [`%s`](%s)\n\n' "$ARTIFACT_NAME" "$ARTIFACT_URL"
    else
      printf 'Workflow artifact: `%s`\n\n' "$ARTIFACT_NAME"
    fi
    printf "| Metric | Value |\n"
    printf "| --- | --- |\n"
    printf '| Cases | `%s` |\n' "$(metric '.cases | length')"
    printf '| Tasks | `%s` |\n' "$(metric '.aggregate.task_count')"
    printf '| Expectations passed | `%s/%s` |\n' "$(metric '.aggregate.expectation_count')" "$(metric '.aggregate.task_count')"
    printf '| Source lines | `%s` |\n' "$(metric '.aggregate.total_task_source_lines')"
    printf '| Selected lines | `%s` |\n' "$(metric '.aggregate.total_selected_lines')"
    printf '| First-read line reduction | `%s%%` |\n' "$(metric '.aggregate.line_reduction')"
    printf '| Estimated tokens | `%s` |\n' "$(metric '.aggregate.total_estimated_tokens')"
    printf '| Max impacted files | `%s` |\n\n' "$(metric '.aggregate.max_impacted_files')"
    if jq -e '.quality_gate? | type == "object"' "$SUMMARY_JSON" >/dev/null; then
      printf '| Route quality gate | `%s >= %s` |\n' \
        "$(metric '.quality_gate.status')" \
        "$(metric '.quality_gate.min_route_quality_score')"
      printf '| Route quality failures | `%s` |\n\n' "$(metric '.quality_gate.failure_count')"
    fi

    printf "| Case | Ref | Tasks | Expectations | Lines | Reduction | First Files |\n"
    printf "| --- | --- | ---: | ---: | ---: | ---: | --- |\n"
    jq -r '
      def first_files:
        [.routes[].first_file] | unique | join(", ");
      .cases[]
      | "| `\(.case)` | `\(.ref[0:12])` | `\(.task_count)` | `\(.expectation_count)` | `\(.total_selected_lines)/\(.total_task_source_lines)` | `\(((1 - (.total_selected_lines / .total_task_source_lines)) * 1000 | round / 10))%` | " + (first_files | gsub("\\|"; "\\|")) + " |"
    ' "$SUMMARY_JSON"
    printf "\n"

    printf "### Representative Routes\n\n"
    printf "| Case | Task | First File | Focus | Question |\n"
    printf "| --- | --- | --- | --- | --- |\n"
    jq -r '
      [
        .cases[] as $case
        | $case.routes[]
        | {
            case: $case.case,
            task,
            first_file,
            first_reading_focus,
            first_reading_question
          }
      ][0:6][]
      | "| `\(.case)` | \(.task | gsub("\\|"; "\\|")) | `\(.first_file)` | \(.first_reading_focus | gsub("\\|"; "\\|")) | \(.first_reading_question | gsub("\\|"; "\\|")) |"
    ' "$SUMMARY_JSON"
    printf "\n"
  } >>"$SUMMARY_FILE"

  echo "public task routing matrix step summary written to $SUMMARY_FILE"
}

main "$@"
