#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/docs/public-task-routing-matrix.md"
CHECK=0
PUBLIC_ARGS=()
TEMP_DIR=""

usage() {
  cat <<'EOF'
usage: scripts/update-public-task-routing-matrix.sh [options] [public matrix options]

Updates or checks the checked-in public task routing matrix snapshot.

Options:
  --check        Fail when docs/public-task-routing-matrix.md is stale.
  --output PATH  Write the normalized snapshot to PATH.
  -h, --help    Show this help text.

All other options are passed through to scripts/public-task-routing-matrix.sh.
Common pass-through options:
  --case NAME
  --root NAME=PATH
  --ref NAME=REF
  --bin PATH
  --force-clone
EOF
}

fail() {
  echo "update public task routing matrix failed: $*" >&2
  exit 1
}

cleanup() {
  if [ -n "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
  fi
}

normalize_markdown() {
  local source="$1"
  local output_dir="$2"
  local target="$3"

  ROOT_DIR="$ROOT_DIR" OUTPUT_DIR="$output_dir" perl -pe '
    BEGIN {
      $root = $ENV{"ROOT_DIR"};
      $output_dir = $ENV{"OUTPUT_DIR"};
    }
    s/\Q$root\E\///g;
    s/\Q$output_dir\E\//<output-dir>\//g;
  ' "$source" |
    awk '
      NR == 1 {
        print;
        print "";
        print "_Snapshot generated by `scripts/update-public-task-routing-matrix.sh` from pinned public repositories._";
        next;
      }
      { print }
    ' >"$target"
}

main() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --check)
        CHECK=1
        shift
        ;;
      --output)
        [ "$#" -ge 2 ] || fail "--output requires a path"
        OUTPUT_FILE="$2"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        PUBLIC_ARGS+=("$1")
        shift
        ;;
    esac
  done

  TEMP_DIR="$(mktemp -d)"
  trap cleanup EXIT INT TERM

  local output_dir generated summary normalized
  output_dir="$TEMP_DIR/public-task-routing-matrix"
  generated="$output_dir/public-task-routing-matrix.md"
  summary="$output_dir/summary.json"
  normalized="$TEMP_DIR/normalized-public-task-routing-matrix.md"

  "$ROOT_DIR/scripts/public-task-routing-matrix.sh" \
    --output-dir "$output_dir" \
    --output "$generated" \
    --summary-json "$summary" \
    "${PUBLIC_ARGS[@]}"

  normalize_markdown "$generated" "$output_dir" "$normalized"

  if [ "$CHECK" = "1" ]; then
    [ -f "$OUTPUT_FILE" ] || fail "snapshot does not exist: $OUTPUT_FILE"
    if command -v git >/dev/null 2>&1; then
      git diff --no-index --quiet "$OUTPUT_FILE" "$normalized" ||
        fail "snapshot is stale; run scripts/update-public-task-routing-matrix.sh"
    else
      cmp -s "$OUTPUT_FILE" "$normalized" ||
        fail "snapshot is stale; run scripts/update-public-task-routing-matrix.sh"
    fi
    echo "public task routing matrix snapshot is current"
    return
  fi

  mkdir -p "$(dirname "$OUTPUT_FILE")"
  cp "$normalized" "$OUTPUT_FILE"
  echo "public task routing matrix snapshot written to $OUTPUT_FILE"
}

main "$@"
