#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC_TASK_ROUTING_MATRIX_SCRIPT="${CODEINSIGHT_PUBLIC_TASK_ROUTING_MATRIX_SCRIPT:-$ROOT_DIR/scripts/public-task-routing-matrix.sh}"
OUTPUT_FILE="$ROOT_DIR/docs/public-task-routing-matrix.md"
SUMMARY_OUTPUT_FILE="$ROOT_DIR/docs/public-task-routing-matrix-summary.json"
CHECK=0
MIN_ROUTE_QUALITY_SCORE="${CODEINSIGHT_UPDATE_PUBLIC_TASK_ROUTING_MATRIX_MIN_ROUTE_QUALITY_SCORE:-}"
PUBLIC_ARGS=()
TEMP_DIR=""

usage() {
  cat <<'EOF'
usage: scripts/update-public-task-routing-matrix.sh [options] [public matrix options]

Updates or checks the checked-in public task routing matrix snapshot.

Options:
  --check                Fail when checked-in snapshots are stale.
  --output PATH          Write the normalized Markdown snapshot to PATH.
  --summary-output PATH  Write the normalized JSON summary snapshot to PATH.
  --min-route-quality-score N
                         Fail when any public route quality score is below N.
  -h, --help             Show this help text.

All other options are passed through to scripts/public-task-routing-matrix.sh.
Common pass-through options:
  --case NAME
  --root NAME=PATH
  --ref NAME=REF
  --bin PATH
  --force-clone

Environment:
  CODEINSIGHT_PUBLIC_TASK_ROUTING_MATRIX_SCRIPT=scripts/public-task-routing-matrix.sh
  CODEINSIGHT_UPDATE_PUBLIC_TASK_ROUTING_MATRIX_MIN_ROUTE_QUALITY_SCORE
EOF
}

fail() {
  echo "update public task routing matrix failed: $*" >&2
  exit 1
}

cleanup() {
  if [ -n "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
  fi
}

normalize_markdown() {
  local source="$1"
  local output_dir="$2"
  local target="$3"

  ROOT_DIR="$ROOT_DIR" OUTPUT_DIR="$output_dir" perl -pe '
    BEGIN {
      $root = $ENV{"ROOT_DIR"};
      $output_dir = $ENV{"OUTPUT_DIR"};
    }
    s/\Q$root\E\///g;
    s/\Q$output_dir\E\//<output-dir>\//g;
  ' "$source" |
    awk '
      NR == 1 {
        print;
        print "";
        print "_Snapshot generated by `scripts/update-public-task-routing-matrix.sh` from pinned public repositories._";
        next;
      }
      /^- Summary JSON:/ {
        print;
        print "- Checked-in JSON summary: [`public-task-routing-matrix-summary.json`](public-task-routing-matrix-summary.json)";
        next;
      }
      { print }
    ' >"$target"
}

normalize_summary_json() {
  local source="$1"
  local target="$2"

  jq \
    --arg root "$ROOT_DIR/" \
    --arg output "<output-dir>/public-task-routing-matrix.md" \
    --arg output_dir "<output-dir>" \
    'def strip_root:
       if startswith($root) then .[($root | length):] else . end;
     .generated_by = "scripts/update-public-task-routing-matrix.sh"
     | .output = $output
     | .output_dir = $output_dir
     | .cases |= map(
         .repository = ("<case-root>/" + .case)
         | .expect_file = (.expect_file | strip_root)
         | .summary_json = ("<output-dir>/" + .case + "/summary.json")
       )' \
    "$source" >"$target"
}

compare_snapshot() {
  local expected="$1"
  local actual="$2"
  local label="$3"

  [ -f "$expected" ] || fail "$label snapshot does not exist: $expected"
  if command -v git >/dev/null 2>&1; then
    git diff --no-index --quiet "$expected" "$actual" ||
      fail "$label snapshot is stale; run scripts/update-public-task-routing-matrix.sh"
  else
    cmp -s "$expected" "$actual" ||
      fail "$label snapshot is stale; run scripts/update-public-task-routing-matrix.sh"
  fi
}

main() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --check)
        CHECK=1
        shift
        ;;
      --output)
        [ "$#" -ge 2 ] || fail "--output requires a path"
        OUTPUT_FILE="$2"
        shift 2
        ;;
      --summary-output)
        [ "$#" -ge 2 ] || fail "--summary-output requires a path"
        SUMMARY_OUTPUT_FILE="$2"
        shift 2
        ;;
      --min-route-quality-score)
        [ "$#" -ge 2 ] || fail "--min-route-quality-score requires a number"
        MIN_ROUTE_QUALITY_SCORE="$2"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        PUBLIC_ARGS+=("$1")
        shift
        ;;
    esac
  done

  TEMP_DIR="$(mktemp -d)"
  trap cleanup EXIT INT TERM

  local output_dir generated summary normalized normalized_summary
  output_dir="$TEMP_DIR/public-task-routing-matrix"
  generated="$output_dir/public-task-routing-matrix.md"
  summary="$output_dir/summary.json"
  normalized="$TEMP_DIR/normalized-public-task-routing-matrix.md"
  normalized_summary="$TEMP_DIR/normalized-public-task-routing-matrix-summary.json"

  if [ -n "$MIN_ROUTE_QUALITY_SCORE" ]; then
    case "$MIN_ROUTE_QUALITY_SCORE" in
      ''|*[!0-9]*)
        fail "--min-route-quality-score must be a non-negative integer"
        ;;
    esac
  fi

  local public_command=(
    "$PUBLIC_TASK_ROUTING_MATRIX_SCRIPT"
    --output-dir "$output_dir"
    --output "$generated"
    --summary-json "$summary"
  )
  if [ -n "$MIN_ROUTE_QUALITY_SCORE" ]; then
    public_command+=(--min-route-quality-score "$MIN_ROUTE_QUALITY_SCORE")
  fi
  if [ "${#PUBLIC_ARGS[@]}" -gt 0 ]; then
    public_command+=("${PUBLIC_ARGS[@]}")
  fi

  "${public_command[@]}"

  normalize_markdown "$generated" "$output_dir" "$normalized"
  normalize_summary_json "$summary" "$normalized_summary"

  if [ "$CHECK" = "1" ]; then
    compare_snapshot "$OUTPUT_FILE" "$normalized" "Markdown"
    compare_snapshot "$SUMMARY_OUTPUT_FILE" "$normalized_summary" "JSON summary"
    echo "public task routing matrix snapshots are current"
    return
  fi

  mkdir -p "$(dirname "$OUTPUT_FILE")"
  mkdir -p "$(dirname "$SUMMARY_OUTPUT_FILE")"
  cp "$normalized" "$OUTPUT_FILE"
  cp "$normalized_summary" "$SUMMARY_OUTPUT_FILE"
  echo "public task routing matrix snapshot written to $OUTPUT_FILE"
  echo "public task routing matrix summary snapshot written to $SUMMARY_OUTPUT_FILE"
}

main "$@"
