#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODEINSIGHT_BIN="${CODEINSIGHT_BIN:-}"
TEMP_DIR=""

fail() {
  echo "update public task routing matrix smoke failed: $*" >&2
  exit 1
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "missing required command: $1"
  fi
}

build_binary_if_needed() {
  if [ -z "$CODEINSIGHT_BIN" ]; then
    require_command cargo
    cargo build --release --locked --manifest-path "$ROOT_DIR/Cargo.toml" >/dev/null
    CODEINSIGHT_BIN="$(cargo metadata --no-deps --format-version 1 --manifest-path "$ROOT_DIR/Cargo.toml" | jq -r '.target_directory')/release/codeinsight"
  fi

  if [ ! -x "$CODEINSIGHT_BIN" ]; then
    fail "CODEINSIGHT_BIN is not executable: $CODEINSIGHT_BIN"
  fi
}

write_file() {
  local path="$1"
  local content="$2"

  mkdir -p "$(dirname "$path")"
  printf "%s\n" "$content" >"$path"
}

cleanup() {
  if [ -n "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
  fi
}

create_express_like_fixture() {
  local repo="$1"

  write_file "$repo/package.json" '{
  "name": "express-like-route-fixture",
  "main": "index.js"
}'
  write_file "$repo/index.js" 'const factory = require("./lib/express");
const application = require("./lib/application");

module.exports = function startup() {
  return factory.createApplication(application.settings());
};'
  write_file "$repo/lib/express.js" 'exports.createApplication = function createApplication(settings) {
  return createExpressApplicationRoutingBehavior(settings);
};

exports.createExpressApplicationRoutingBehavior = function createExpressApplicationRoutingBehavior(settings) {
  // Express application routing behavior mounts the router and route table.
  return { route: "/health", router: "express", application: "app", settings };
};'
  write_file "$repo/lib/application.js" 'exports.settings = function settings() {
  return { env: "test", middleware: ["logger"] };
};

exports.middleware = function middleware(request, next) {
  return next(request);
};'
}

main() {
  require_command jq
  build_binary_if_needed

  TEMP_DIR="$(mktemp -d)"
  trap cleanup EXIT INT TERM

  local repo snapshot summary_snapshot
  repo="$TEMP_DIR/repo"
  snapshot="$TEMP_DIR/public-task-routing-matrix.md"
  summary_snapshot="$TEMP_DIR/public-task-routing-matrix-summary.json"
  create_express_like_fixture "$repo"

  CODEINSIGHT_BIN="$CODEINSIGHT_BIN" "$ROOT_DIR/scripts/update-public-task-routing-matrix.sh" \
    --output "$snapshot" \
    --summary-output "$summary_snapshot" \
    --case express \
    --root "express=$repo" \
    --token-budget 1600 >/dev/null

  grep -Fq 'Snapshot generated by `scripts/update-public-task-routing-matrix.sh`' "$snapshot" ||
    fail "snapshot should include generation note"
  grep -Fq "expectations: 4/4" "$snapshot" ||
    fail "snapshot should include expectation pass count"
  grep -Fq "line_reduction:" "$snapshot" ||
    fail "snapshot should include aggregate line reduction"
  grep -Fq 'Summary JSON: `<output-dir>/summary.json`' "$snapshot" ||
    fail "snapshot should normalize summary path"
  grep -Fq 'docs/task-routing-expectations/express.tsv' "$snapshot" ||
    fail "snapshot should normalize expectation file path"
  if grep -Fq "$TEMP_DIR" "$snapshot"; then
    fail "snapshot should not include temporary absolute paths"
  fi
  jq -e \
    '.generated_by == "scripts/update-public-task-routing-matrix.sh"
      and .status == "pass"
      and .aggregate.task_count == 4
      and .aggregate.expectation_count == 4
      and .aggregate.total_task_source_lines > .aggregate.total_selected_lines
      and .aggregate.line_reduction > 0
      and .cases[0].repository == "<case-root>/express"
      and .cases[0].summary_json == "<output-dir>/express/summary.json"
      and .cases[0].expect_file == "docs/task-routing-expectations/express.tsv"' \
    "$summary_snapshot" >/dev/null ||
    fail "summary snapshot should be normalized JSON evidence"

  CODEINSIGHT_BIN="$CODEINSIGHT_BIN" "$ROOT_DIR/scripts/update-public-task-routing-matrix.sh" \
    --check \
    --output "$snapshot" \
    --summary-output "$summary_snapshot" \
    --case express \
    --root "express=$repo" \
    --token-budget 1600 >/dev/null

  echo "update public task routing matrix smoke passed"
}

main "$@"
